### ISSUE TITLE
Pressing X for hands up the player is then stuck on the bed

### ISSUE THREAD

**Issue by duckysuck** [ohqpr/qphospital#16]
### Developement Issue

Yes

### Description

After choosing to lay in a bed, if the player presses X to put their hands up it cancels the laying down and the player is stuck on the bed unable to get off.

### Reproduction

qtarget onto the bed
press X for handsup (providing you have it mapped to that, most do)

**Comment by ohqpr** [comment]
Hello, to get up from off of the bed it is key mapped to key "F", not "X". https://github.com/ohqpr/qphospital/blob/30864e0d769a3e6790d2d137748a9f4daada27c9/client/main.lua#L275
